package com.interviewengine.session.domain;

/**
 * Where a question in a session's bank came from (PRD v2.1 §7.5.8).
 *
 * <p>Both sources live in the same bank and every question carries one of these
 * tags. The distinction is not cosmetic — it changes how the question is treated
 * and how its score should be read:
 *
 * <ul>
 *   <li>{@link #EMPLOYER} questions are always included and never sampled out,
 *       and they occupy the core segment first, so that every candidate for the
 *       job is asked them and stays comparable.</li>
 *   <li>They bypass the quality critic but never the safety filter. If an
 *       employer wants to ask something the quality critic would score poorly,
 *       that is their call; safety is not.</li>
 *   <li>The report labels them, because a recruiter reading a low Technical
 *       score needs to know whether it came from our questions or theirs.</li>
 * </ul>
 */
public enum QuestionSource {

    /** Generated by the question workflow from the JD and résumé. */
    AI,

    /** Supplied by the employer against the job opening. */
    EMPLOYER
}
