-- =============================================================================
-- V007__session_create_interview_sessions_table.sql
-- depends on: V001__company_create_companies_table.sql
--             V005__job_create_job_openings_table.sql
--             V006__candidate_create_candidates_table.sql
-- =============================================================================

CREATE TABLE interview_sessions (
    id                UUID         NOT NULL DEFAULT gen_random_uuid(),
    company_id        UUID         NOT NULL,
    job_opening_id    UUID         NOT NULL,
    candidate_id      UUID         NOT NULL,
    invite_token_hash VARCHAR(255) NOT NULL,
    invite_expires_at TIMESTAMPTZ  NOT NULL,

    -- Recall.ai bot identifier, assigned asynchronously after the bot joins the call.
    -- NULL until the BotDispatchService receives the bot.joined webhook.
    recall_bot_id     VARCHAR(255),

    -- Google Meet URL generated by Recall.ai for this session.
    -- Required by the BotDispatchService to instruct the bot which meeting to join.
    -- NULL until the bot is dispatched.
    google_meet_url   VARCHAR(512),

    -- Session lifecycle state machine:
    --   INVITED    → invite sent, candidate has not yet started
    --   STARTED    → bot joined, interview in progress
    --   COMPLETED  → interview ended normally; evaluation pipeline triggered
    --   EXPIRED    → invite window elapsed without candidate starting (SessionExpiryJob)
    --   ERROR      → bot join failure or evaluation pipeline failure; requires review
    --   CANCELLED  → employer explicitly cancelled before candidate started
    status            VARCHAR(50)  NOT NULL DEFAULT 'INVITED',

    -- AI question generation pipeline state for this session.
    -- The interview bot reads questions_json when status transitions to STARTED.
    -- PENDING      → generation not yet started (default on INSERT)
    -- IN_PROGRESS  → LLM call in flight
    -- DONE         → questions_json is populated and valid
    -- FAILED       → pipeline error; session transitions to ERROR
    question_generation_status VARCHAR(50) NOT NULL DEFAULT 'PENDING',

    -- Pre-generated question set as a JSON array. Written exactly once after the
    -- LLM pipeline completes; read exactly once when the bot starts the interview.
    -- Structure: [{"order": 1, "text": "...", "dimension": "TECHNICAL"}, ...]
    -- NULL while question_generation_status is PENDING, IN_PROGRESS, or FAILED.
    -- MUST check question_generation_status before reading this field.
    -- JSONB structural constraints (jsonb_typeof, jsonb_array_length) are added
    -- in V024 to keep constraint logic reviewable independently of table structure.
    questions_json    JSONB,

    started_at        TIMESTAMPTZ,
    ended_at          TIMESTAMPTZ,

    -- Structured error identifier for ERROR state sessions.
    -- Examples: BOT_JOIN_TIMEOUT, EVALUATION_PIPELINE_FAILURE, TRANSCRIPTION_ERROR.
    -- Drives the error display in the admin panel and retry logic.
    error_code        VARCHAR(100),

    -- Human-readable error detail for incident debugging. Free-form text from the
    -- service layer; not displayed in the employer UI, only in admin tooling.
    error_message     TEXT,

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT pk_interview_sessions
        PRIMARY KEY (id),

    -- enables composite FK from child tables (e.g. session_notes) to enforce
    -- that a referenced session belongs to the same company as the child row
    CONSTRAINT uq_interview_sessions_company_id_id
        UNIQUE (company_id, id),

    CONSTRAINT fk_interview_sessions_companies
        FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE RESTRICT,

    -- composite FK: guarantees the job opening belongs to the same company
    -- requires uq_job_openings_company_id_id on job_openings(company_id, id) — added in V005
    CONSTRAINT fk_interview_sessions_job_openings
        FOREIGN KEY (company_id, job_opening_id) REFERENCES job_openings (company_id, id) ON DELETE RESTRICT,

    -- composite FK: guarantees the candidate belongs to the same company
    -- requires uq_candidates_company_id_id on candidates(company_id, id) — added in V006
    CONSTRAINT fk_interview_sessions_candidates
        FOREIGN KEY (company_id, candidate_id) REFERENCES candidates (company_id, id) ON DELETE RESTRICT,

    -- raw token is never stored; only the hash is persisted
    CONSTRAINT uq_interview_sessions_invite_token_hash
        UNIQUE (invite_token_hash),

    CONSTRAINT ck_interview_sessions_status_valid
        CHECK (status IN ('INVITED', 'STARTED', 'COMPLETED', 'EXPIRED', 'ERROR', 'CANCELLED')),

    CONSTRAINT ck_interview_sessions_question_generation_status_valid
        CHECK (question_generation_status IN ('PENDING', 'IN_PROGRESS', 'DONE', 'FAILED')),

    -- invite must expire strictly after row creation
    CONSTRAINT ck_interview_sessions_future_expiry
        CHECK (invite_expires_at > created_at),

    -- if both timestamps are recorded, the session must end after it started
    CONSTRAINT ck_interview_sessions_ended_after_started
        CHECK (ended_at IS NULL OR started_at IS NULL OR ended_at > started_at),

    -- a session cannot end without having started
    CONSTRAINT ck_interview_sessions_started_before_ended
        CHECK (ended_at IS NULL OR started_at IS NOT NULL)
);
